#!/bin/sh

# Log some extra information at the beginning of a suspend/resume cycle.

echo "!!!!!!!!!!!wifi $1 $2" > /dev/kmsg

case "$1-$2" in
       pre-hibernate|pre-suspend)
	       ifconfig wlan0 down
               ;;
       post-hibernate|post-suspend)
	       ifconfig wlan0 up
               ;;
       *) exit $NA
               ;;
esac
